language: node_js
node_js:
  - 'node'
script:
  - yarn test
  - yarn run codecov
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: npm
  email: george.aidonidis@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
